### ISSUE TITLE
Cannot connect - docker not installed

### ISSUE THREAD

**Issue by darrylhebbes** [masasam/emacs-counsel-tramp#1]
Hello, thanks for a great plugin.

I have followed the install instructions and tried all possible settings but when I run M-x counsel-tramp I get "counsel-tramp: ’docker’ is not installed" in Emacs 25.3. Any ideas, perhaps its a setting in Docker I missing... but Docker works

**Comment by masasam** [comment]
Hi @darrylhebbes .
Is docker-tramp working?
emacs 25.3 require the following settings.
(require 'docker-tramp-compat)
See https://github.com/emacs-pe/docker-tramp.el

**Comment by masasam** [comment]
Hi @darrylhebbes .
Do you see the $PATH with docker from emacs?
I recommend you are going to install exec-path-from-shell.
See https://github.com/purcell/exec-path-from-shell.

**Comment by masasam** [comment]
Hi @darrylhebbes .
Can you run docker without sudo?
docker-tramp does not work with sudo docker.
So you need the following settings in your terminal.
sudo usermod -aG docker ${USER}

**Comment by darrylhebbes** [comment]
Hi, many thanks for your support - it was the settings of the  **exec-path-from-shell** package, I had recently moved my $PATH to zshenv and so I needed to add   **(exec-path-from-shell-copy-env "path")** now its working ;-)
