### ISSUE TITLE
Can't find recent remote file by counsel recentf

### ISSUE THREAD

**Issue by Zilong-Li** [masasam/emacs-counsel-tramp#7]
Hi,

Thanks for your great work on this.

But I can't use counsel recentf to find the recently opened remote files as shown in your screenshot. How do you setup this?

**Comment by masasam** [comment]
Hi @Zilong-Li .
Thank you for comment.
My counsel/ivy settings are [here](https://github.com/masasam/dotfiles/blob/master/.emacs.d/inits/04counsel.el).
If you open the directory with counsel-tramp and then open the file, it seems to remain in Recent Files.

**Comment by Zilong-Li** [comment]
Thank you @masasam. 

I fixed it. I just found somehow "/ssh" was put into recentf-exclude in my configures.
