### ISSUE TITLE
Make `docker` optional

### ISSUE THREAD

**Issue by swarnendubiswas** [masasam/emacs-counsel-tramp#9]
I do not use `docker` often, but I do use `ssh` extensively. However, the `counsel-tramp` package throws an error if `docker` is not installed. Can we avoid the hard dependency on `docker` even for newer versions of Emacs?

**Comment by masasam** [comment]
Hi @swarnendubiswas !
Thank you for report.
Changed so that it can be started without installing docker at https://github.com/masasam/emacs-counsel-tramp/commit/70dcc6b9da5e76fefbc92646e7d780b2a06ca93f .
Melpa package will be updated in about 6 hours, so please wait.
